#
# Haiku's infrastructure
#
# WARNING: Defining "ports" means these ports will be open to the public internet!
#          Docker controls the firewall. Docker is life.
#
version: "2.2"
services:
  traefik:
    # Traefik connects to docker and reads labels to form routes
    # Traefik also handles letsencrypt renewals
    image: traefik:latest
    restart: always
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:z
      - ${TRAEFIK_TOML}:/traefik.toml:z
      - traefik_acme:/acme:z
  discourse:
    image: haiku/discuss
    entrypoint: /sbin/boot
    environment:
      LANG: en_US.UTF-8
      RAILS_ENV: production
      UNICORN_WORKERS: 6
      UNICORN_SIDEKIQS: 1
      DOCKER_USE_HOSTNAME: "true"
    expose:
      - "80"
    volumes:
      - discourse_shared:/shared:z
      - discourse_logs:/var/log:z
    restart: on-failure
    labels:
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:discuss.${DOMAIN}"
  gerrit:
    # Disable in test environments
    ports:
      - "94.130.158.38:22:29418" # PROD-ONLY
    image: haiku/gerrit
    volumes:
      - gerrit_data:/var/gerrit/review_site:z
      - ./data/gerrit/hooks:/var/gerrit/review_site/hooks:z
    restart: on-failure
    environment:
      AUTH_TYPE: OAUTH
      GITWEB_TYPE: cgit
      JAVA_HEAPLIMIT: 1024m
      # OAUTH_GITHUB_CLIENT_ID: XXXONBOOTSTRAPXXX
      # OAUTH_GITHUB_CLIENT_SECRET: XXXONBOOTSTRAPXX
      SMTP_SERVER: smtp
      SMTP_SERVER_PORT: 25
      SMTP_FROM: Gerrit <review@review.haiku-os.org>
      SMTP_CONNECT_TIMEOUT: 30
    labels:
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:review.${DOMAIN}"
      - "traefik.basic.port=8080"
  cgit:
    image: haiku/cgit
    restart: on-failure
    volumes:
      - gerrit_data:/var/git
    environment:
      CGIT_TITLE: "Haiku's repositories"
      CGIT_DESC: 'Presented by cgit on Docker'
      # check section-from-path in cgit docs
      CGIT_VROOT: '/'
      CGIT_SECTION_FROM_STARTPATH: 1
    labels:
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:cgit.${DOMAIN},git.${DOMAIN}"
      - "traefik.basic.frontend.redirect.regex=cgit.${DOMAIN}/(.*)"
      - "traefik.basic.frontend.redirect.replacement=git.${DOMAIN}/$$1"
      - "traefik.basic.port=80"
  irker:
    image: haiku/irker
    restart: on-failure
  pootle:
    image: haiku/pootle
    restart: on-failure
    volumes:
      - pootle_data:/var/pootle:z
    depends_on:
      - postgres
      - redis
      - smtp
    labels:
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:i18n.${DOMAIN};PathPrefixStrip:/pootle/"
      - "traefik.basic.port=80"
  portsmirror:
    image: haiku/ports-mirror
    restart: on-failure
    volumes:
      - ports_mirror:/ports-mirror
    labels:
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:ports-mirror.${DOMAIN}"
      - "traefik.basic.port=80"
  postgres:
    image: postgres:9.6
    restart: on-failure
    environment:
      POSTGRES_USER: "baron"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:4.0
    command: redis-server --appendonly yes
    restart: on-failure
    volumes:
      - redis_data:/data:z
  smtp:
    image: mwader/postfix-relay
    restart: on-failure
    volumes:
      - smtp_keys:/etc/opendkim/keys:z
    environment:
      - POSTFIX_myhostname=maui.haiku-os.org
      - OPENDKIM_DOMAINS=maui.haiku-os.org discuss.haiku-os.org review.haiku-os.org git.haiku-os.org
  trac:
    image: haiku/trac
    restart: on-failure
    volumes:
      - trac_data:/var/trac:z
    depends_on:
      - postgres
      - smtp
    labels:
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:dev.${DOMAIN}"
      - "traefik.basic.port=80"
  userguide:
    image: haiku/userguide
    restart: on-failure
    volumes:
      - userguide_data:/var/userguide:z
    depends_on:
      - postgres
      - smtp
    labels:
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:i18n.${DOMAIN};PathPrefixStrip:/userguide/"
      - "traefik.basic.port=80"
  www-i18n:
    image: dragas/thttpd
    restart: on-failure
    volumes:
      - ./data/static-html/i18n:/var/www/http:z
    labels:
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:i18n.${DOMAIN}"
      # redirect /pootle & /userguide to forward to proper containers
      - "traefik.basic.frontend.redirect.regex=i18n.${DOMAIN}/(pootle|userguide)$$"
      - "traefik.basic.frontend.redirect.replacement=i18n.${DOMAIN}/$$1/"
      - "traefik.basic.port=80"
  www-build:
    image: dragas/thttpd
    restart: on-failure
    volumes:
      - ./data/static-html/build:/var/www/http:z
    labels:
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:build.${DOMAIN}"
      - "traefik.basic.port=80"
  www-repo:
    image: haiku/nginx
    restart: on-failure
    volumes:
      - ./data/www-repo:/etc/nginx/conf.d:z
      - ./data/static-html/repo:/usr/share/nginx/html:z
    labels:
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:eu.hpkg.${DOMAIN}"
      - "traefik.basic.port=80"
  download:
    image: haiku/download
    restart: on-failure
    volumes:
      - s3_secrets:/secrets:z
      - s3_data:/data:z
    labels:
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:download.${DOMAIN}"
      - "traefik.basic.frontend.redirect.regex=download.${DOMAIN}/(haiku-repositories|haikuports-repositories)/(.*)$$"
      - "traefik.basic.frontend.redirect.replacement=cdn.${DOMAIN}/$$1/$$2"
      - "traefik.basic.port=80"
  haikudepotserver:
    image: haiku/haikudepotserver:1.0.105
    restart: on-failure
    volumes:
      - hds_secrets:/secrets:z
    depends_on:
      - postgres
    labels:
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:depot.${DOMAIN}"
      - "traefik.basic.port=8080"
  buildbot:
    image: haiku/buildbot-master
    hostname: buildbot
    restart: on-failure
    volumes:
      - buildbot_config:/var/lib/buildbot:z
      - ./data/buildbot/master.cfg:/var/lib/buildbot/master.cfg:z
      - /var/run/docker.sock:/var/run/docker.sock:z
      - s3_data:/data:z
    ports:
      - 9989:9989
    labels:
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:build.${DOMAIN};PathPrefixStrip:/buildbot/"
      - "traefik.basic.port=80"
  cdn:
    image: minio/minio
    restart: on-failure
    command: server /data
    volumes:
      - s3_data:/data:z
      - minio_config:/root/.minio/:z
    labels:
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:cdn.${DOMAIN}"
      - "traefik.basic.port=9000"
  repo-mirror:
    image: haiku/repo-mirror
    restart: on-failure
    volumes:
      - s3_data:/repo-data:ro,z
      - ./data/repo-mirror:/repo-whitelist:ro,z
    ports:
      - 12000:12000
  prometheus:
    image: prom/prometheus
    restart: on-failure
    volumes:
      - ./data/metrics/prometheus.yml:/etc/prometheus/prometheus.yml:z
      - prometheus_data:/prometheus:z
  grafana:
    image: grafana/grafana
    restart: on-failure
    environment:
      GF_SMTP_ENABLED: "true"
      GF_SMTP_HOST: "smtp:25"
      GF_SMTP_FROM_ADDRESS: "admin@metrics.${DOMAIN}"
      GF_SERVER_ROOT_URL: "https://metrics.${DOMAIN}/grafana/"
    volumes:
      - grafana_data:/var/lib/grafana
    labels:
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:metrics.${DOMAIN};PathPrefixStrip:/grafana/"
      - "traefik.basic.port=3000"
  fathom:
    image: usefathom/fathom:latest
    depends_on:
      - postgres
    restart: on-failure
    volumes:
      - fathom_secrets:/var/lib/fathom
    command: /app/fathom --config=/var/lib/fathom/config.env server
    labels:
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:metrics.${DOMAIN}"
      - "traefik.basic.port=8080"
volumes:
  traefik_acme:
  buildbot_config:
  fathom_secrets:
  gerrit_data:
  pootle_data:
  ports_mirror:
  postgres_data:
  userguide_data:
  trac_data:
  redis_data:
  s3_data:
  s3_secrets:
  hds_secrets:
  prometheus_data:
  grafana_data:
  minio_config:
  discourse_shared:
  discourse_logs:
  smtp_keys:
