version: "2"
services:
  router:
    image: haiku/nginx-router
    ports:
      - "0.0.0.0:443:443"
      - "0.0.0.0:80:80"
    volumes:
      - ./data/router:/etc/nginx/conf.d:z
      - /etc/letsencrypt:/etc/letsencrypt:z
      - ./data/static-html:/static-html:z
      - ports_mirror:/ports-mirror:z
      - download_data:/download-data:z
      - repo_data:/repo-data:z
    restart: on-failure
    depends_on:
      - gerrit
      - cgit
  gerrit:
    # Uncomment in test environments
    ports:
      - "94.130.158.38:22:29418" # PROD-ONLY
    image: haiku/gerrit
    volumes:
      - gerrit_data:/var/gerrit/review_site
      - ./data/gerrit/hooks:/var/gerrit/review_site/hooks:z
    restart: on-failure
    environment:
      - AUTH_TYPE=OAUTH
      - GITWEB_TYPE=cgit
      #- OAUTH_GITHUB_CLIENT_ID=XXXONBOOTSTRAPXXX
      #- OAUTH_GITHUB_CLIENT_SECRET=XXXONBOOTSTRAPXX
  cgit:
    image: haiku/cgit
    restart: on-failure
    volumes:
      - gerrit_data:/var/git
    environment:
      CGIT_TITLE: "Haiku's repositories"
      CGIT_DESC: 'Presented by cgit on Docker'
      # check section-from-path in cgit docs
      CGIT_VROOT: '/'
      CGIT_SECTION_FROM_STARTPATH: 1
  irker:
    image: haiku/irker
    restart: on-failure
  pootle:
    image: haiku/pootle
    restart: on-failure
    volumes:
      - pootle_data:/var/pootle:z
    depends_on:
      - postgres
      - redis
      - smtp
  portsmirror:
    image: haiku/ports-mirror
    restart: on-failure
    volumes:
      - ports_mirror:/ports-mirror
  postgres:
    image: postgres:9.6
    restart: on-failure
    environment:
      POSTGRES_USER: "baron"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  redis:
    image: redis:4.0
    restart: on-failure
  smtp:
    image: mwader/postfix-relay
    restart: on-failure
    environment:
      - POSTFIX_myhostname=maui.haiku-os.org
  trac:
    image: haiku/trac
    restart: on-failure
    volumes:
      - trac_data:/var/trac:z
    depends_on:
      - postgres
      - smtp
  userguide:
    image: haiku/userguide
    restart: on-failure
    volumes:
      - userguide_data:/var/userguide:z
    depends_on:
      - postgres
      - smtp
  buildbot:
    #image: buildbot/buildbot-master:v1.1.0
    image: rodrigc6/buildbot
    hostname: buildbot
    restart: on-failure
    volumes:
      - buildbot_config:/var/lib/buildbot:z
      - ./data/buildbot/master.cfg:/var/lib/buildbot/master.cfg:z
    ports:
      - '0.0.0.0:9989:9989'
  cdn:
    image: haiku/cdn
    restart: on-failure
    volumes:
      - repo_data:/repo-data:z
      - ./data/cdn/rsync-whitelist:/etc/rsync-whitelist:ro
    ports:
      - '0.0.0.0:12000:12000'
volumes:
  buildbot_config:
  gerrit_data:
  pootle_data:
  ports_mirror:
  postgres_data:
  userguide_data:
  trac_data:
  download_data:
  repo_data:
