apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
    name: "do-block-storage-persist"
    provisioner: "dobs.csi.digitalocean.com"
  name: do-block-storage-persist
provisioner: dobs.csi.digitalocean.com
reclaimPolicy: Retain
volumeBindingMode: Immediate
